language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

env:
  - DJANGO_SETTINGS_MODULE="purbeurre.settings"
  - ENV_APP="lab"


services:
  - postgresql

# safelist
branches:
  only:
    - master

script:
  - pytest test/unit
