language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.settings"

services:
  - postgresql

# safelist
branches:
  only:
    - testing

script:
  - python manage.py test
