language: python
python:
  - '3.8.6'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.settings"

services:
  - postgresql

# safelist
branches:
  only:
    - testing

script:
  - ./manage.py test
